nits from prod review

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -14,9 +14,47 @@ jobs:
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
+      - name: Check Filenames
+        shell: bash
+        run: |
+          whitelist=(
+            "ACKNOWLEDGEMENTS.md"
+            "CNAME"
+            "COLLECTION_POLICY.md"
+            "CONTRIBUTING.md"
+            "CONTRIBUTORS.md"
+            "README.md"
+            "Gemfile"
+            "Gemfile.lock"
+            "_data/cssCacheToken.yml"
+          )
+          invalid_files=()
+          readarray -t tracked_files < <(git diff-tree --no-commit-id --diff-filter=d --diff-merges=1 --name-only -r HEAD)
+          for file in "${tracked_files[@]}"; do
+            if [[ -f "$file" ]]; then
+              filename=$(basename "$file")
+              # Check if file is whitelisted
+              if [[ " ${whitelist[@]} " =~ " $filename " ]]; then
+                continue
+              fi
+              echo "Checking $file..."
+              if ! grep -qE '^[+0-9a-z_\.-]+$' <<< "$filename"; then
+                invalid_files+=("$file")
+              fi
+            fi
+          done
+          if [[ ${#invalid_files[@]} -gt 0 ]]; then
+            echo "Invalid characters found in the following files:"
+            for file in "${invalid_files[@]}"; do
+              echo "$file"
+            done
+            exit 1
+          else
+            echo "All files have valid names."
+            exit 0
+          fi
       - name: Normalize Unicode in the Previous Commit
         uses: buddhist-uni/normalized-unicode-action@v1
-      - run: bash ./scripts/check-filenames.bash
       - name: Install node
         uses: actions/setup-node@v3
         with:
