protest doc and new cache buster

diff --git a/.github/workflows/cache.yaml b/.github/workflows/cache.yaml
--- a/.github/workflows/cache.yaml
+++ b/.github/workflows/cache.yaml
@@ -1,12 +1,38 @@
 name: Cache Buster
 on:
-  - deployment_status
+  workflow_run:
+    workflows:
+      - "pages-build-deployment"
+      - "pages build and deployment"
+    types: [completed]
 jobs:
   cloudflare:
-    name: CloudFlare Cache
-    if: github.event.deployment_status.state == "success"
+    name: "Purge CloudFlare Cache"
     runs-on: ubuntu-latest
     steps:
       - name: "POST cache_purge:everything"
+        shell: bash
         run: |
-          curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache" -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" -H "Content-Type:application/json" --data '{"purge_everything":true}'
+          echo "curling the api..."
+          HTTP_RESPONSE=$(curl -sSX POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache" -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" -H "Content-Type:application/json" -w "HTTP_STATUS:%{http_code}" --data '{"purge_everything":true}')
+          HTTP_BODY=$(echo "${HTTP_RESPONSE}" | sed -E 's/HTTP_STATUS\:[0-9]{3}$//')
+          HTTP_STATUS=$(echo "${HTTP_RESPONSE}" | tr -d '\n' | sed -E 's/.*HTTP_STATUS:([0-9]{3})$/\1/')
+          if [ "${HTTP_STATUS}" -eq "200" ]; then
+            SUCCESS=$(echo ${HTTP_BODY} | python3 -c "import sys, json;print(json.load(sys.stdin)['success'])")
+            if [ "${SUCCESS}" = "True" ]; then
+              echo "Successfully purged!"
+              echo "::group::Raw response"
+              echo "${HTTP_BODY}"
+              echo "::endgroup::"
+              exit 0
+            else
+              echo "Unsuccessful purge!"
+              echo "API response was:"
+              echo "${HTTP_BODY}"
+              exit 1
+            fi
+          else
+            echo "Request failed. API response was ($HTTP_STATUS): "
+            echo "${HTTP_BODY}"
+            exit 1
+          fi
